# -*- coding: utf-8 -*-
"""DipanshuTest28Jan

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nPTdAlnKe58vALXvh6EtRwRrux91jgzc

1. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.
"""

class Vehicle:
    def __init__(self, distance, capacity):
        self.distance = distance
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    def fare(self):
        fare_bus = self.capacity * 100
        total_fare = fare_bus + (0.1 *fare_bus)
        return total_fare
Hamro_Bus = Bus(10, 25)
print("The total Bus fare is:", Hamro_Bus.fare())

"""2. Write a Python program to read a given CSV file as a list.

"""

import csv
with open('cities.csv', 'r') as file:
    data_file = csv.reader(file)
    for row in data_file:
        print(row)

"""3. Write a Python program to display first 5 rows from COVID-19 dataset. Also print the dataset information and check the missing values.
Dataset link:- 
https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv
"""

import pandas as pd
covid_19_data= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')
print(covid_19_data)
print("\nDataset information:")
print(covid_19_data.info())
print("\nMissing data information:")
print(covid_19_data.isna().sum())

"""4. Write a numpy program to create an element-wise comparison (greater, greater equal, less and less equal) of two given arrays.

"""

import numpy as np
x = np.array([32, 62])
y = np.array([17, 86])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

"""5. Write a Python program to draw a line with suitable label in the x axis, y axis and a title.

"""

import matplotlib.pyplot as plt
X = range(1, 100)
Y = [value * 2 for value in X]
print("Values of X:")
print(*range(1,100))
print("Values of Y (twice of X):")
print(Y)
# Plot lines and/or markers to the Axes.
plt.plot(X, Y)
# Set the x axis label of the current axis.
plt.xlabel('x - axis')
# Set the y axis label of the current axis.
plt.ylabel('y - axis')
# Set a title
plt.title('Number of Covid Cases.')
# Display the figure.
plt.show()